version: "3"
services:
  api-database:
    image: mongo
    container_name: "api-database"
    ports:
      - 27017:27017
  notesApp:
    image: rahdocker321/notesappimage
    ports:
      - 9091:8080
    links:
      - api-database


